name: deploy to server and reboot the bot

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.0"
          cache: npm
      - name: Start build
        run: echo Build started.
      - name: Install dependencies
        run: npm ci
      - name: Generate ssh key
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy
        run: rsync -av -rlptgoD --delete --exclude ".git/" --exclude ".env" --exclude "*.db" --exclude "*.db-shm" --exclude "*.db-wal" --exclude "dat/backup" --exclude "dat/images" --exclude "dat/texts" --exclude "dat/voices" -e "ssh -i ./key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${SSH_PORT}" ./ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
